# Generated by Django 4.2.5 on 2023-09-11 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_alter_product_category_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Electronics', 'Electronics'), ('Clothing', 'Clothing'), ('Books', 'Books'), ('Home', 'Home'), ('Kids', 'Kids'), ('Cosmetics', 'Cosmetics'), ('Fashion', 'Fashion')], max_length=20),
        ),
    ]
