# Generated by Django 4.2.5 on 2023-09-12 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0003_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tagline',
            field=models.CharField(blank=True, help_text="A short and crisp tagline. Ex: 'Sustainable Materials', 'Classic'", max_length=50, null=True),
        ),
    ]
